ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.2"
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
        - id: check-added-large-files
          args: ['--maxkb=2000']
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: check-yaml
        - id: debug-statements
        - id: end-of-file-fixer
        - id: mixed-line-ending
        - id: trailing-whitespace
