[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool]
name = "my_streamlit_app"
version = "0.1.0"
description = "A simple Streamlit app"
authors = ["Your Name <your.email@example.com>"]

[tool.dependencies]
python = "^3.8"
streamlit = "^1.0.0"
