# .streamlit/config.toml

[server]
#headless = true  # Run Streamlit in headless mode, ideal for cloud deployments
port = 8501      # Define the port for the Streamlit app
#enableCORS = false  # Disable CORS if deploying within the same domain

[theme]
base= "dark"
primaryColor = "3d405b"
backgroundColor = "#f4f1de"
secondaryBackgroundColor = "b8d6c7"
textColor = "#3d405b"
font = "sans serif"

[browser]
gatherUsageStats = false  # Disable collection of usage statistics for privacy
